### ISSUE TITLE
I found a bug!

### ISSUE THREAD

**Issue by aldisio** [aldisiomedeiros-lab/cobaia-2021-pub#2]
blablablablablablablablablablablablablabla

**Comment by aldisiomedeiros-lab** [comment]
blablablablablablablablablablablablablabla

**Comment by aldisio** [comment]
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla

**Comment by aldisiomedeiros-lab** [comment]
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla
blablablablablablablablablablablablablabla

**Comment by aldisiomedeiros-lab** [comment]
fixed!
